### ISSUE TITLE
2.0.2 release failing to deploy

### ISSUE THREAD

**Issue by srnly** [fortinet/fortigate-autoscale#20] opened 2020-01-24 22:14 UTC
Just tried to deploy the new 2.0.2 template but stack deployment failed with these errors:

The following resource(s) failed to create: [FgtAsgVpcEndpoint].
FgtAsgVpcEndpoint | CREATE_FAILED | VPC Endpoint vpce-0d6a14c4f005210e4 did not stabilize.

**Comment by kkawatra09** [comment] 2020-01-27 20:21
I'm having the same issue

**Comment by JaydenLiang** [comment] 2020-01-27 23:57
I have completed another deployment stack in ap-south-1, and it was completed successfully so I am curious anything was missing to me.

Please give me more information using the format:
AWS region:
general steps you did to launch your stack that caused such failure:
deployment parameters:

**Comment by srnly** [comment] 2020-01-28 00:39
AWS region: us-east-2

Parameters:
AvailabilityZones
us-east-2a,us-east-2b
-
CustomIdentifier
fgtASG
-
FgtAsgCooldown
300
-
FgtAsgDesiredCapacityByol
2
-
FgtAsgDesiredCapacityPayg
0
-
FgtAsgHealthCheckGracePeriod
300
-
FgtAsgMaxSizeByol
2
-
FgtAsgMaxSizePayg
6
-
FgtAsgMinSizeByol
2
-
FgtAsgMinSizePayg
0
-
FgtAsgScaleInThreshold
25
-
FgtAsgScaleOutThreshold
80
-
FortiGateAdminCidr
<redacted>
-
FortiGateAdminPort
10443
-
FortiGateInstanceType
c5.large
-
FortiGatePskSecret
****
-
FortiOSVersion
6.2.3
-
GetLicenseGracePeriod
600
-
HeartBeatDelayAllowance
2
-
HeartBeatInterval
30
-
HeartBeatLossCount
3
-
InternalLoadBalancerDnsName
-
-
InternalLoadBalancingOptions
add a new internal load balancer
-
InternalTargetGroupHealthCheckPath
/
-
KeyPairName
FGT-KP
-
LifecycleHookTimeout
480
-
LoadBalancingHealthCheckThreshold
3
-
LoadBalancingTrafficPort
443
-
LoadBalancingTrafficProtocol
HTTPS
-
MasterElectionTimeout
300
-
PrivateSubnet1Cidr
172.31.128.0/24
-
PrivateSubnet2Cidr
172.31.129.0/24
-
PublicSubnet1Cidr
172.31.130.0/24
-
PublicSubnet2Cidr
172.31.131.0/24
-
ResourceTagPrefix
FGT
-
S3BucketName
habit-fgt
-
S3KeyPrefix
deployment-package/
-
VpcCidr
172.31.0.0/16
-


[https://www.securedretail.com/email/srn-shield-email.png]
[https://www.securedretail.com/email/divider_red-wide.png]
[https://www.securedretail.com/email/lester-yang.png]
Lester Yang
Information Security Engineer
[Email]<mailto:lyang@securedretail.com>[Website]<https://www.securedretail.com/>[Facebook]<https://www.facebook.com/securedretail/>[Twitter]<https://twitter.com/securedretail>[LinkedIn]<https://www.linkedin.com/company/securedretail/>
Secured Retail Networks, Inc.
26000 Towne Centre Drive, Ste 100, Foothill Ranch, CA 92610
Direct: 949.390.6734    SRN Support: 949.390.6703

**Comment by JaydenLiang** [comment] 2020-01-28 01:44
Hi @srnly , I couldn't reproduce this issue myself with the given parameters. If you can describe the general steps you did to launch your stack, it'd help us idendify the issue. My appreciation.

**Comment by srnly** [comment] 2020-01-28 15:09
HI @JaydenLiang , I used the autoscale-new-vpc template and launched the stack following the steps in https://docs.fortinet.com/vm/aws/fortigate/6.2/aws-cookbook/6.2.0/543390/deploying-auto-scaling-on-aws-without-transit-gateway-integration.

**Comment by JaydenLiang** [comment] 2020-06-25 20:55
Hi @srnly I still haven't heard from you regarding this issue.
We have a new release recently. Will you be able to verify your deployment again and provide with us more information? Otherwise, I will close this issue in a month.

**Comment by JaydenLiang** [comment] 2020-09-10 16:52
close it because of no more feedback.

**Closed by JaydenLiang** 2020-09-10 16:52 UTC
